# Generated by Django 3.1.5 on 2021-01-20 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingitem',
            options={'ordering': ['training', 'position']},
        ),
    ]
