openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /training-plan/api/exercises/:
    get:
      operationId: listExercises
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Exercise'
          description: ''
      tags:
      - training-plan
    post:
      operationId: createExercise
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Exercise'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Exercise'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Exercise'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exercise'
          description: ''
      tags:
      - training-plan
  /training-plan/api/exercises/{id}/:
    get:
      operationId: retrieveExercise
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this exercise.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exercise'
          description: ''
      tags:
      - training-plan
    put:
      operationId: updateExercise
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this exercise.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Exercise'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Exercise'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Exercise'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exercise'
          description: ''
      tags:
      - training-plan
    patch:
      operationId: partialUpdateExercise
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this exercise.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Exercise'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Exercise'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Exercise'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exercise'
          description: ''
      tags:
      - training-plan
    delete:
      operationId: destroyExercise
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this exercise.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - training-plan
  /training-plan/api/trainings/:
    get:
      operationId: listTrainings
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Training'
          description: ''
      tags:
      - training-plan
    post:
      operationId: createTraining
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Training'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Training'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Training'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Training'
          description: ''
      tags:
      - training-plan
  /training-plan/api/trainings/{id}/:
    get:
      operationId: retrieveTraining
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Training'
          description: ''
      tags:
      - training-plan
    put:
      operationId: updateTraining
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Training'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Training'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Training'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Training'
          description: ''
      tags:
      - training-plan
    patch:
      operationId: partialUpdateTraining
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Training'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Training'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Training'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Training'
          description: ''
      tags:
      - training-plan
    delete:
      operationId: destroyTraining
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - training-plan
  /training-plan/api/training-items/:
    get:
      operationId: listTrainingItems
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TrainingItem'
          description: ''
      tags:
      - training-plan
    post:
      operationId: createTrainingItem
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrainingItem'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TrainingItem'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TrainingItem'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrainingItem'
          description: ''
      tags:
      - training-plan
  /training-plan/api/training-items/{id}/:
    get:
      operationId: retrieveTrainingItem
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this training item.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrainingItem'
          description: ''
      tags:
      - training-plan
    put:
      operationId: updateTrainingItem
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this training item.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrainingItem'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TrainingItem'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TrainingItem'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrainingItem'
          description: ''
      tags:
      - training-plan
    patch:
      operationId: partialUpdateTrainingItem
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this training item.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrainingItem'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TrainingItem'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TrainingItem'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrainingItem'
          description: ''
      tags:
      - training-plan
    delete:
      operationId: destroyTrainingItem
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this training item.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - training-plan
  /training-plan/api/user/:
    get:
      operationId: retrieveUser
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
      tags:
      - training-plan
  /training-plan/api/register/:
    post:
      operationId: createRegister
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Register'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Register'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Register'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Register'
          description: ''
      tags:
      - training-plan
  /training-plan/api/login/:
    post:
      operationId: createLogin
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Login'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Login'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Login'
          description: ''
      tags:
      - training-plan
  /training-plan/api/logout/:
    post:
      operationId: createLogout
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - training-plan
components:
  schemas:
    Exercise:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 200
        description:
          type: string
        file:
          type: string
          format: binary
      required:
      - name
      - description
    Training:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 200
        description:
          type: string
        training_items:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              exercise_id:
                type: integer
              position:
                type: integer
                maximum: 2147483647
                minimum: -2147483648
              reps_count:
                type: integer
                maximum: 2147483647
                minimum: -2147483648
            required:
            - exercise_id
            - reps_count
      required:
      - name
      - description
    TrainingItem:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        exercise_id:
          type: integer
        training_id:
          type: integer
        position:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
        reps_count:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
      required:
      - exercise_id
      - training_id
      - reps_count
    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+\z
          maxLength: 150
        email:
          type: string
          format: email
          maxLength: 254
      required:
      - username
    Register:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+\z
          maxLength: 150
        email:
          type: string
          format: email
          maxLength: 254
        password:
          type: string
          writeOnly: true
          maxLength: 128
      required:
      - username
      - email
      - password
    Login:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
      - username
      - password
